export default function getAllProducts() {
  return [
    {
      id: "NAF-1-07-FMEN-001",
      slug: "nike-air-force-1-07-men",
      name: "Nike Air Force 1 '07",
      category: "Men's Shoe",
      categorySlug: "men-shoes",
      price: 1_549_000,
      stock: 100,
      imageUrl: "/assets/images/AIR-FORCE-1-07.png",
      description: `The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colours and the perfect amount of flash to make you shine.`,
    },
    {
      id: "NAF-1-07-FMEN-LV8-002",
      slug: "nike-air-force-1-07-lv8-men",
      name: "Nike Air Force 1 '07 LV8",
      category: "Men's Shoe",
      categorySlug: "men-shoes",
      price: 1_909_000,
      stock: 5,
      imageUrl: `/assets/images/AIR+FORCE+1+'07+LV8.png`,
      description: `Comfortable, durable and timeless—it's number 1 for a reason. The classic '80s construction pairs with bold details for style that tracks whether you're on court or on the go.`,
    },
    {
      id: "NAF-1-07-FWOMEN-003",
      slug: "nike-air-force-1-07-women",
      name: "Nike Air Force 1 '07",
      category: "Women's Shoe",
      categorySlug: "women-shoes",
      price: 1_909_000,
      stock: 0,
      imageUrl: `/assets/images/WMNS+AIR+FORCE+1+'07.jpeg`,
      description: `Comfortable, durable and timeless—it's number 1 for a reason. The classic '80s construction pairs a warm suede upper with neutral accents for style that tracks whether you're on court or on the go.`,
    },
    {
      id: "NL-II-FMEN-LV8",
      slug: "nike-lunargato-II-men",
      name: "Nike Lunargato II",
      category: "Men's Shoe",
      categorySlug: "men-shoes",
      price: 1_646_000,
      stock: 10,
      imageUrl: `/assets/images/NIKE+LUNARGATO+II.png`,
      description: `The Nike Lunar Gato II is ideal for the small-sided game. The soft leather in the forefoot has a smooth, natural feel for precision touch. The cushioning in the midsole feels springy and responsive, while the rubber tread gives you traction for quick cuts on indoor surfaces.`,
    },
    {
      id: "NMS-1O-ELITE-SE-FG-FMEN",
      slug: "nike-mercurial-superfly-10-se-fg",
      name: "Nike Mercurial SuperFly 10 Elite SE FG",
      category: "Men's Shoe",
      categorySlug: "men-shoes",
      price: 4_869_000,
      stock: 5,
      imageUrl: `/assets/images/AIR+FORCE+1+'07+LV8.png`,
      description: `Obsessed with speed? So are the game's biggest stars. That's why we made this Elite boot with an improved 3/4-length Air Zoom unit. It gives you and the sport's fastest players the propulsive feel needed to break through the back line. The result is the most responsive Mercurial we've ever made, because you demand greatness from yourself and your footwear.`,
    },
  ];
}
